init python:
    class splunk_video(object):
        def __init__(self, url, title, about):
            self.title = title
            self.url = url
            self.about = about

label InitializeSplunkVideos:
    # Auto-generated Ren'Py script for YouTube video data

    default video1 = splunk_video("https://www.youtube.com/watch?v=QiV_wviNYJg", "Zeek Sensor Tutorial | Switching Logs to Json Format", "Join this channel to get access to perks: https://www.youtube.com/channel/UCdSFSscTkK8oGd_kD_eENFw/join.")
    $ listOfYoutube.append(video1)
    default video2 = splunk_video("https://www.youtube.com/watch?v=zDcmPGbl7gw", "Splunk Raw Tutorial", "Splunk tutorial on the metadata field _raw. Join this channel to get access to early release of videos and exclusive training videos ...")
    $ listOfYoutube.append(video2)
    default video3 = splunk_video("https://www.youtube.com/watch?v=SPYc4AygV4M", "Splunk Top / Rare Command", "Splunk tutorial for how the top and rare command can help provide analytical insight into the most commonly and least commonly ...")
    $ listOfYoutube.append(video3)
    default video4 = splunk_video("https://www.youtube.com/watch?v=FVorWMJ-EX4", "Splunk Meta Hosts Tutorial", "Tutorial videos on how to use the Splunk Metadata fields. This video will focus on the host metadata field. Join this channel to get ...")
    $ listOfYoutube.append(video4)
    default video5 = splunk_video("https://www.youtube.com/watch?v=RGhjXm18SyQ", "Splunk Tutorial | Generate Inventory List with MV Commands #FADS", "Playlist Link for All Daily Trainings https://www.youtube.com/playlist?list=PLFF93FRoUwXGPIh4E5mBvbVxrpjGRUqIO Log ...")
    $ listOfYoutube.append(video5)
    default video6 = splunk_video("https://www.youtube.com/watch?v=JqhNPdLlB0M", "Splunk Tutorial | Converting Epoch Time to Human Readable Text #FADS", "To view all videos in the playlist on Splunk Tutorials for Creating Searches use the link: ...")
    $ listOfYoutube.append(video6)
    default video7 = splunk_video("https://www.youtube.com/watch?v=ZruKXTAH9jM", "Splunk Tutorial | Collect How to Save Your Search Results to an Index #FADS", "Playlist Link for All Daily Trainings https://www.youtube.com/playlist?list=PLFF93FRoUwXGPIh4E5mBvbVxrpjGRUqIO Log ...")
    $ listOfYoutube.append(video7)
    default video8 = splunk_video("https://www.youtube.com/watch?v=icgvmkHAD6k", "Splunk Simplified - Free Analytic Daily Share | metadata type=sourcetypes", "Playlist Link for All Daily Trainings https://www.youtube.com/playlist?list=PLFF93FRoUwXGPIh4E5mBvbVxrpjGRUqIO We are ...")
    $ listOfYoutube.append(video8)
    default video9 = splunk_video("https://www.youtube.com/watch?v=9IPtIOe8FG8", "Splunk Tutorial | Save Results to a CSV #FADS", "Playlist Link for All Daily Trainings https://www.youtube.com/playlist?list=PLFF93FRoUwXGPIh4E5mBvbVxrpjGRUqIO Log ...")
    $ listOfYoutube.append(video9)
    default video10 = splunk_video("https://www.youtube.com/watch?v=Wpou1ipGnO0", "Top Secrets of Splunk: Mastering the &#39;top&#39; Command for Certification!", "\"Unlock the power of Splunk's 'top' command with this quick tutorial! Perfect for those preparing for the Splunk certification, we'll ...")
    $ listOfYoutube.append(video10)
    default video11 = splunk_video("https://www.youtube.com/watch?v=IgdmrNeQXEU", "Splunk Tutorial | Using CSV Lookup to Refine Inventory List #FADS", "Playlist Link for All Daily Trainings https://www.youtube.com/playlist?list=PLFF93FRoUwXGPIh4E5mBvbVxrpjGRUqIO Log ...")
    $ listOfYoutube.append(video11)
    default video12 = splunk_video("https://www.youtube.com/watch?v=eVxqW9W8H5g", "Splunk Tutorial | Converting Epoch Time to Human Readable Text Part 2 #FADS", "To view all videos in the playlist on Splunk Tutorials for Creating Searches use the link: ...")
    $ listOfYoutube.append(video12)
    default video13 = splunk_video("https://www.youtube.com/watch?v=aJMpRBhXmXs", "Splunk Tutorial | Searching Splunk For Dashboard Views #FADS", "To view all videos in the playlist on Splunk Tutorials for Creating Searches use the link: ...")
    $ listOfYoutube.append(video13)
    default video14 = splunk_video("https://www.youtube.com/watch?v=HZKDnEiyfVk", "Splunk Tutorial | Refresh Config Settings #FADS", "To view all videos in the playlist on Splunk Tutorials for Creating Searches use the link: ...")
    $ listOfYoutube.append(video14)
    default video15 = splunk_video("https://www.youtube.com/watch?v=Ii8aPMW_Jpk", "Intro to Splunk SOAR Phantom | How to Customize a SOAR App", "Playlist Link for SOAR Videos https://youtube.com/playlist?list=PLFF93FRoUwXH_7yitxQiSUhJlZE7Ybmfu This is the a ...")
    $ listOfYoutube.append(video15)
    default video16 = splunk_video("https://www.youtube.com/watch?v=VJDizpfg4Mw", "Splunk Tutorial | Stats Putting it All Together to Profile Network #FADS", "To view all videos in the playlist on Splunk Tutorials for Creating Searches use the link: ...")
    $ listOfYoutube.append(video16)
    default video17 = splunk_video("https://www.youtube.com/watch?v=xVrpE0unGco", "Fast vs. Verbose Search in Splunk: Key Differences Explained", "Welcome to our channel! In this video, we break down the key differences between Fast and Verbose search modes in Splunk, ...")
    $ listOfYoutube.append(video17)
    default video18 = splunk_video("https://www.youtube.com/watch?v=teCpjIPaFsI", "Unlock the Power of Field Command in Splunk! | SPL Tutorial for Data-Driven Insights", "In this Let's Learn SPL video, we're talking about the fields command! Unlike many other SPL commands designed to help you ...")
    $ listOfYoutube.append(video18)
    default video19 = splunk_video("https://www.youtube.com/watch?v=Iwn0ZvXJtE8", "Splunk Tutorial | Transpose Command #FADS", "Playlist Link for All Daily Trainings https://www.youtube.com/playlist?list=PLFF93FRoUwXGPIh4E5mBvbVxrpjGRUqIO Log ...")
    $ listOfYoutube.append(video19)
    default video20 = splunk_video("https://www.youtube.com/watch?v=nn3_ZbTZ4Xw", "Splunk Tutorial For Beginners | Common Mistakes | Default Landing Page for all Splunk Users", "Splunk users will come to your environment with all levels of expertise. The worst thing you can do is to just put the default search ...")
    $ listOfYoutube.append(video20)
    default video21 = splunk_video("https://www.youtube.com/watch?v=lo4_MIfTJzI", "Splunk Tutorial | Using a Lookup to Find System Not Reporting to Splunk #FADS", "Playlist Link for All Daily Trainings https://www.youtube.com/playlist?list=PLFF93FRoUwXGPIh4E5mBvbVxrpjGRUqIO Log ...")
    $ listOfYoutube.append(video21)
    default video22 = splunk_video("https://www.youtube.com/watch?v=WouGxslDN2s", "Splunk Dedup Command Tutorial", "Splunk tutorial explaining how to use the dedup command and also the same dedup command can be done quicker with a stats ...")
    $ listOfYoutube.append(video22)
    default video23 = splunk_video("https://www.youtube.com/watch?v=RQVQP-7PNtg", "Splunk Meta Index Tutorial", "Tutorial videos on how to use the Splunk Metadata fields. This video will focus on the host metadata field. Join this channel to get ...")
    $ listOfYoutube.append(video23)
    default video24 = splunk_video("https://www.youtube.com/watch?v=-uZ3imNwbLE", "Splunk Tutorial | Detecting Potential Spear Phishing #FADS", "To view all videos in the playlist on Splunk Tutorials for Creating Searches use the link: ...")
    $ listOfYoutube.append(video24)
    default video25 = splunk_video("https://www.youtube.com/watch?v=RZuFjBvBOGU", "Splunk Tutorial | How to Detect / Search for IPv6 Addresses #FADS", "Log Analysis Made Easy (L.A.M.E.) Free Analytic Daily Share (F.A.D.S) will help you navigate Splunk better, use data models, ...")
    $ listOfYoutube.append(video25)
    default video26 = splunk_video("https://www.youtube.com/watch?v=OaYYcm2Vgz4", "Microsoft PowerShell For Beginners | Viewing Results Using Out-Gridview", "PowerShell Out-Gridview cmdlet provides a user the ability to sort and filter the results in an easy to use gui. This video ...")
    $ listOfYoutube.append(video26)
    default video27 = splunk_video("https://www.youtube.com/watch?v=IHJ0Iy95RRE", "Splunk Tutorial | Analyzing Domain Names For Randomness (Entropy) #FADS", "To view all videos in the playlist on Splunk Tutorials for Creating Searches use the link: ...")
    $ listOfYoutube.append(video27)
    default video28 = splunk_video("https://www.youtube.com/watch?v=Zt2_Hg4B5q8", "Splunk System Admin Interview Preparation | savedsearches.conf Common Settings", "A sound understanding of the props files that governs your Splunk instance is an invaluable skill for any splunk admin. This and ...")
    $ listOfYoutube.append(video28)
    default video29 = splunk_video("https://www.youtube.com/watch?v=U94mcCSXNt8", "Splunk System Admin Interview Preparation | apps.conf and limits.conf Common Settings", "A sound understanding of the conf files that governs your Splunk instance is an invaluable skill for any splunk admin. This and the ...")
    $ listOfYoutube.append(video29)
    default video30 = splunk_video("https://www.youtube.com/watch?v=GbOH7bX3uYI", "ProxMox an Intro Video To Free Virtualization Software For Cyber Security Testing", "Join this channel to get access to perks: https://www.youtube.com/channel/UCdSFSscTkK8oGd_kD_eENFw/join.")
    $ listOfYoutube.append(video30)
    default video31 = splunk_video("https://www.youtube.com/watch?v=I-iI9BIdMG0", "Splunk Tutorial For Beginners | Creating a Basic EventGen System in Splunk Replacing Timestamp", "The ability to have Splunk generate logs for a development system can be an integral part of creating a training environment for ...")
    $ listOfYoutube.append(video31)
    default video32 = splunk_video("https://www.youtube.com/watch?v=yO8kefdh7fY", "Free Splunk Tutorial On Using Wildcards For Searching Indexes", "This video will cover how to use wildcards in Splunk. This is part of a Splunk Tutorial Playlist to improving your Splunk SPL ...")
    $ listOfYoutube.append(video32)
    default video33 = splunk_video("https://www.youtube.com/watch?v=Lfuy0vbOOKk", "Splunk Tutorial | Makeresults create your own custom data in SPL #FADS", "Playlist Link for All Daily Trainings https://www.youtube.com/playlist?list=PLFF93FRoUwXGPIh4E5mBvbVxrpjGRUqIO Log ...")
    $ listOfYoutube.append(video33)
    default video34 = splunk_video("https://www.youtube.com/watch?v=W0ZIpYuTasI", "Top Secrets of Splunk: Mastering the &#39;top&#39; Command for Certification! #splunkcertification", "Unlock the power of Splunk's 'top' command with this quick tutorial! Perfect for those preparing for the Splunk certification, we'll ...")
    $ listOfYoutube.append(video34)
    default video35 = splunk_video("https://www.youtube.com/watch?v=_QrfM0N60Cc", "How to Setup A Large Splunk Environment With Ease", "L.A.M.E. Creations has created a Windows Desktop app that makes the creation of a complex Splunk environment simple.")
    $ listOfYoutube.append(video35)
    default video36 = splunk_video("https://www.youtube.com/watch?v=Sz6Du7uPNYg", "Splunk System Admin Interview Preparation | macros.conf Common Settings", "A sound understanding of the props files that governs your Splunk instance is an invaluable skill for any splunk admin. This and ...")
    $ listOfYoutube.append(video36)
    default video37 = splunk_video("https://www.youtube.com/watch?v=OoGbJhTUU4I", "Splunk Tutorial | Using StreamStats to Improve MakeResults #FADS", "Playlist Link for All Daily Trainings https://www.youtube.com/playlist?list=PLFF93FRoUwXGPIh4E5mBvbVxrpjGRUqIO Join this ...")
    $ listOfYoutube.append(video37)
    default video38 = splunk_video("https://www.youtube.com/watch?v=EA7qHheXCBw", "PowerShell and How to Manipulate Strings", "PowerShell provides lots of methods for manipulating strings. This tutorial will attempt to provide instruction on how to use them.")
    $ listOfYoutube.append(video38)
    default video39 = splunk_video("https://www.youtube.com/watch?v=UG1bynI70ls", "How to Activate EventGen in Splunk", "Log Analysis Made Easy Training App uses random logs generated through a tool called EventGen. This video will demonstrate ...")
    $ listOfYoutube.append(video39)
    default video40 = splunk_video("https://www.youtube.com/watch?v=KIpfjRvdWL0", "Splunk Meta Source Tutorial", "Splunk tutorial video on the metadata field source. Join this channel to get access to early release of videos and exclusive training ...")
    $ listOfYoutube.append(video40)
    default video41 = splunk_video("https://www.youtube.com/watch?v=V1FLDnnED6I", "Splunk Enterprise Security Free Training | Data Model Example - Web", "L.A.M.E. Creations has scoured the internet for guidance on the Enterprise Security SIEM from Splunk but has found most of the ...")
    $ listOfYoutube.append(video41)
    default video42 = splunk_video("https://www.youtube.com/watch?v=a7Bvf44AjPY", "Splunk Tutorial For Beginners | Common Mistakes | Deploying KV Lookups with a Deployment Server", "The time may arise that a person decides to push a KV Lookup to a remote Splunk system using a Deployment Server. A major ...")
    $ listOfYoutube.append(video42)
    default video43 = splunk_video("https://www.youtube.com/watch?v=HIGMuEammdE", "Crack the Code: Understanding Splunk&#39;s Search Result Display! #splunkcertification", "Join this channel to get access to perks: https://www.youtube.com/channel/UCdSFSscTkK8oGd_kD_eENFw/join.")
    $ listOfYoutube.append(video43)
    default video44 = splunk_video("https://www.youtube.com/watch?v=JavUl0kDfJA", "PowerShell Tutorial: Working with Variables and Objects Explained", "Welcome to our channel! In this video, we explore the fundamentals of working with variables and objects in PowerShell. Whether ...")
    $ listOfYoutube.append(video44)
    default video45 = splunk_video("https://www.youtube.com/watch?v=5sFRdgUP3Fk", "Splunk How To Create Reports Tutorial 101", "This tutorial will cover the most basic concepts of how to build a report, schedule a report, accelerate a report, how to integrate ...")
    $ listOfYoutube.append(video45)
    default video46 = splunk_video("https://www.youtube.com/watch?v=Im-egqSaJWk", "Splunk Tutorial | Create a Heartbeat Monitor #FADS", "Playlist Link for All Daily Trainings https://www.youtube.com/playlist?list=PLFF93FRoUwXGPIh4E5mBvbVxrpjGRUqIO Log ...")
    $ listOfYoutube.append(video46)
    default video47 = splunk_video("https://www.youtube.com/watch?v=HvBmfd0o-0c", "Splunk Tutorial | Quickly Search All Sources #FADS", "Playlist Link for All Daily Trainings https://www.youtube.com/playlist?list=PLFF93FRoUwXGPIh4E5mBvbVxrpjGRUqIO Log ...")
    $ listOfYoutube.append(video47)
    default video48 = splunk_video("https://www.youtube.com/watch?v=MY6xxL5lEUg", "Splunk Tutorial | ForEach Queries in Splunk #FADS", "To view all videos in the playlist on Splunk Tutorials for Creating Searches use the link: ...")
    $ listOfYoutube.append(video48)
    default video49 = splunk_video("https://www.youtube.com/watch?v=3b2rceG9MIU", "Cribl Logstream Pipeline Overview", "Cribl Logstream provides an extensive capability to manage and manipulate logs. This video will cover some of the basic things ...")
    $ listOfYoutube.append(video49)
    default video50 = splunk_video("https://www.youtube.com/watch?v=7KDRGprI9Iw", "Splunk Tutorial For Beginners | Creating a Basic EventGen System in Splunk Replacing IPs", "The ability to have Splunk generate logs for a development system can be an integral part of creating a training environment for ...")
    $ listOfYoutube.append(video50)
    default video51 = splunk_video("https://www.youtube.com/watch?v=P84FlCraiDk", "Splunk Tutorial | Using Stats Range to Fingerprint Network Devices #FADS", "To view all videos in the playlist on Splunk Tutorials for Creating Searches use the link: ...")
    $ listOfYoutube.append(video51)
    default video52 = splunk_video("https://www.youtube.com/watch?v=uxSksSryQgc", "Splunk Tutorial For Beginners | KV Store Bug / Mistake That Will Purge All Content From KV Store", "At the risk of calling a software feature a bug, this video will demonstrate how an non-informed user can accidentally purge all of ...")
    $ listOfYoutube.append(video52)
    default video53 = splunk_video("https://www.youtube.com/watch?v=xtB79DVogO4", "Splunk Tutorial | Stats Avg Median and Mode to Profile Network Traffic #FADS", "To view all videos in the playlist on Splunk Tutorials for Creating Searches use the link: ...")
    $ listOfYoutube.append(video53)
    default video54 = splunk_video("https://www.youtube.com/watch?v=ROmkbNvg3zM", "Zeek Sensor Tutorial | Cribl Pipeline for Modifying Ingested Logs", "Join this channel to get access to perks: https://www.youtube.com/channel/UCdSFSscTkK8oGd_kD_eENFw/join.")
    $ listOfYoutube.append(video54)
    default video55 = splunk_video("https://www.youtube.com/watch?v=n27s80wXr_A", "I Can&#39;t Read the Content on the Page - What Do I Do?", "I recently ran into a problem where I could not read the BIOS page on my computer. I needed to change some settings but I could ...")
    $ listOfYoutube.append(video55)
    default video56 = splunk_video("https://www.youtube.com/watch?v=WBzKUYAfGsk", "Splunk Data Models - Why Should You Use Them?", "Splunk has provided data models to allow you to group together similar types of logs. Datamodels can be confusing when you first ...")
    $ listOfYoutube.append(video56)
    default video57 = splunk_video("https://www.youtube.com/watch?v=PwriGyeCiEg", "Navigation Pages Made Simple", "Suggestion / Tutorial for a way of tracking the IP addresses of multiple systems in your network. To view the rest of the videos in ...")
    $ listOfYoutube.append(video57)
    default video58 = splunk_video("https://www.youtube.com/watch?v=7X6vNTlAuEo", "Splunk Fundamentals - Ingest Logs and Get Them CIM Compliant | Example 2", "This tutorial will take the PFSense firewall logs and ingest them into Splunk through Cribl. We will discuss how to get a sample set ...")
    $ listOfYoutube.append(video58)
    default video59 = splunk_video("https://www.youtube.com/watch?v=BmB-TPxEfQU", "Splunk Tutorial | Using a Lookup to Find New Systems in a Sourcetype #FADS", "Playlist Link for All Daily Trainings https://www.youtube.com/playlist?list=PLFF93FRoUwXGPIh4E5mBvbVxrpjGRUqIO Log ...")
    $ listOfYoutube.append(video59)
    default video60 = splunk_video("https://www.youtube.com/watch?v=6nxjAkYC-zM", "Crack the Code: Understanding Splunk&#39;s Search Result Display!", "Struggling with how Splunk shows search results? This quick tutorial is your key to acing that certification question. Here's what ...")
    $ listOfYoutube.append(video60)
    default video61 = splunk_video("https://www.youtube.com/watch?v=Ik-AMveGnMM", "Splunk System Admin Interview Preparation | props.conf and transforms.conf Common Settings", "A sound understanding of the props files that governs your Splunk instance is an invaluable skill for any splunk admin. This and ...")
    $ listOfYoutube.append(video61)
    default video62 = splunk_video("https://www.youtube.com/watch?v=ktKKWM4lHHE", "Splunk Tutorial | Finding Potential Network Scanners #FADS", "To view all videos in the playlist on Splunk Tutorials for Creating Searches use the link: ...")
    $ listOfYoutube.append(video62)
    default video63 = splunk_video("https://www.youtube.com/watch?v=zlcY-5FvaN0", "Microsoft PowerShell For Beginners | Filtering, Sorting, and Viewing Windows EventLogs", "A beginner tutorial on how to use Microsoft PowerShell and how to retrieve Windows EventLogs. When piped to the out-gridview ...")
    $ listOfYoutube.append(video63)
    default video64 = splunk_video("https://www.youtube.com/watch?v=UVqFTMQwUqA", "Splunk Meta Time Tutorial", "A tutorial to discuss the metatdata field in Splunk _time. Join this channel to get access to early release of videos and exclusive ...")
    $ listOfYoutube.append(video64)
    default video65 = splunk_video("https://www.youtube.com/watch?v=GGw9oRE_bOQ", "Splunk Tutorial | ForEach Queries in Splunk Example 2 #FADS", "To view all videos in the playlist on Splunk Tutorials for Creating Searches use the link: ...")
    $ listOfYoutube.append(video65)
    default video66 = splunk_video("https://www.youtube.com/watch?v=f4_tdCIIUmY", "Splunk Regex Tutorial | Creating CIDR Notation from IP Addresses", "Join this channel to get access to perks: https://www.youtube.com/channel/UCdSFSscTkK8oGd_kD_eENFw/join.")
    $ listOfYoutube.append(video66)
    default video67 = splunk_video("https://www.youtube.com/watch?v=-B0cceXSJGc", "Splunk Tutorial For Beginners | Stats vs Eventstats vs Streamstats Command in Splunk", "This video is an audience request to outline the difference between the stats command, streamstats command and the eventstats ...")
    $ listOfYoutube.append(video67)
    default video68 = splunk_video("https://www.youtube.com/watch?v=iK2jfHwq628", "How to Write Conditional Statements in PowerShell", "PowerShell lets you evaluate conditions using equals, not equals, greater than, less than, contains, like, matches, and other ...")
    $ listOfYoutube.append(video68)
    default video69 = splunk_video("https://www.youtube.com/watch?v=63T1urviuyI", "PowerShell If - ElseIf - Else and Switch Statements", "This powershell tutorial will walk you through different logic control statements to allow powershell to take different actions ...")
    $ listOfYoutube.append(video69)
    default video70 = splunk_video("https://www.youtube.com/watch?v=TWYY5teg0VI", "How to Create and Maintain Dashboard Documentation Within Splunk", "I have often been asked to document my analytics and dashboards within Splunk. Over time, I have learned to leverage Splunk to ...")
    $ listOfYoutube.append(video70)
    default video71 = splunk_video("https://www.youtube.com/watch?v=ABEAoAQqmLc", "Splunk Tutorial | Finding Systems No Longer Reporting To Splunk #FADS", "Playlist Link for All Daily Trainings https://www.youtube.com/playlist?list=PLFF93FRoUwXGPIh4E5mBvbVxrpjGRUqIO We are ...")
    $ listOfYoutube.append(video71)
    default video72 = splunk_video("https://www.youtube.com/watch?v=0jxBg05jvDI", "How To Set up a Network to Learn Cyber Computer Security", "This tutorial explains why I created the L.A.M.E. Channel and also explains how I set up my home network to simulate a ...")
    $ listOfYoutube.append(video72)
    default video73 = splunk_video("https://www.youtube.com/watch?v=HVNMgCqSGnI", "Splunk Using a Custom Dashboard and KVs to Create a Data Dictionary", "Splunk can ingest all sorts of sourcetypes. This tutorial will walk through an exercise of creating a KV Store and than using a ...")
    $ listOfYoutube.append(video73)
    default video74 = splunk_video("https://www.youtube.com/watch?v=-VojasmHz70", "Zeek Sensor Tutorial | Ingesting the Logs With Cribl", "Join this channel to get access to perks: https://www.youtube.com/channel/UCdSFSscTkK8oGd_kD_eENFw/join.")
    $ listOfYoutube.append(video74)
    default video75 = splunk_video("https://www.youtube.com/watch?v=nubRKc-geIo", "Mastering Time Manipulation in PowerShell: A Comprehensive Guide", "Welcome to our channel! In this video, we dive deep into the world of PowerShell and explore various techniques for manipulating ...")
    $ listOfYoutube.append(video75)
    default video76 = splunk_video("https://www.youtube.com/watch?v=khCNEMi8vho", "Splunk Tutorial | Length Command #FADS", "Playlist Link for All Daily Trainings https://www.youtube.com/playlist?list=PLFF93FRoUwXGPIh4E5mBvbVxrpjGRUqIO We are ...")
    $ listOfYoutube.append(video76)
    default video77 = splunk_video("https://www.youtube.com/watch?v=DGk2MCWmFGY", "PowerShell and How To Get Help on How To Use Any Cmdlet", "PowerShell has a cmdlet Get-Help that will provide you all of the documentation for using that cmdlet. It is also a great tool for ...")
    $ listOfYoutube.append(video77)
    default video78 = splunk_video("https://www.youtube.com/watch?v=behISUiYR-o", "Splunk System Admin Interview Preparation | deploymentclient.conf Common Settings", "A sound understanding of the props files that governs your Splunk instance is an invaluable skill for any splunk admin. This and ...")
    $ listOfYoutube.append(video78)
    default video79 = splunk_video("https://www.youtube.com/watch?v=WDPENL7lb_s", "Splunk Tutorial | Streamstats to find systems not reporting to Splunk #FADS", "Playlist Link for All Daily Trainings https://www.youtube.com/playlist?list=PLFF93FRoUwXGPIh4E5mBvbVxrpjGRUqIO We are ...")
    $ listOfYoutube.append(video79)
    default video80 = splunk_video("https://www.youtube.com/watch?v=UBfE5fEkSkM", "Splunk Schedules: Unlocking the Power of Alerts with Reports! #splunkcertification", "Discover how scheduled reports in Splunk are more than just data summaries in this certification prep video: • Why triggering ...")
    $ listOfYoutube.append(video80)
    default video81 = splunk_video("https://www.youtube.com/watch?v=IcHApZh9eEg", "Splunk Eval Command", "Splunk Tutorial for learning how to use the eval command. Visit our discord channel to post questions and suggestions for what ...")
    $ listOfYoutube.append(video81)
    default video82 = splunk_video("https://www.youtube.com/watch?v=7lkVXwIZEOY", "Splunk Tutorial | Renaming Multiple Fields With One Rename Command", "To view all videos in the playlist on Splunk Tutorials for Creating Searches use the link: ...")
    $ listOfYoutube.append(video82)
    default video83 = splunk_video("https://www.youtube.com/watch?v=Aq-K4xHm3SA", "Splunk System Admin Interview Preparation | inputs.conf Common Settings", "A sound understanding of the props files that governs your Splunk instance is an invaluable skill for any splunk admin. This and ...")
    $ listOfYoutube.append(video83)
    default video84 = splunk_video("https://www.youtube.com/watch?v=D2UtBLsx5Wo", "PowerShell and the Get-Alias Cmdlet", "If you are struggling to understand peoples online queries, get-alias may be a great tool to unlocking the mysteries of their script.")
    $ listOfYoutube.append(video84)
    default video85 = splunk_video("https://www.youtube.com/watch?v=8zIqfUrkaKg", "Splunk Tutorial On How To Restrict Search by Date", "This video will focus on using a human readable time like April 1st 1999 as a date in your SPL query. This is part of a Splunk ...")
    $ listOfYoutube.append(video85)
    default video86 = splunk_video("https://www.youtube.com/watch?v=AWj-tr_p53Q", "Splunk Tutorial For Beginners | Common Mistakes | Run Splunk as Root", "We are going to outline some of the common mistakes that we see occuring in Splunk environments. We will cover SPL mistakes ...")
    $ listOfYoutube.append(video86)
    default video87 = splunk_video("https://www.youtube.com/watch?v=RS0iBsvKogE", "Splunk Tutorials | timewrap #FADS", "Playlist Link for All Daily Trainings https://www.youtube.com/playlist?list=PLFF93FRoUwXGPIh4E5mBvbVxrpjGRUqIO We are ...")
    $ listOfYoutube.append(video87)
    default video88 = splunk_video("https://www.youtube.com/watch?v=Da5ix_taCgc", "Arrays and PowerShell", "Arrays are an integral part of data manipulation. This video will cover how many of the ways that Arrays can be used in Powershell ...")
    $ listOfYoutube.append(video88)
    default video89 = splunk_video("https://www.youtube.com/watch?v=jhKmYT3SEac", "Free Tools To Use For Creating Quality YouTube Videos", "Based off requests from others, I have put together a tutorial on how I make my YouTube videos. I use the following tools on my ...")
    $ listOfYoutube.append(video89)
    default video90 = splunk_video("https://www.youtube.com/watch?v=vRRXnt89y7E", "Master the Basics of SPL with the Powerful Search Command!", "Are you ready to level up your Splunk game? In this tutorial, we'll explore the Search Command—the foundation of Splunk ...")
    $ listOfYoutube.append(video90)
    default video91 = splunk_video("https://www.youtube.com/watch?v=KUwXcTYOKDA", "Unlock Splunk on the Go: How to Use the Splunk Mobile App on Your Smartphone!", "In this video, I'll show you how to use the Splunk Mobile App to access your Splunk instance directly from your smartphone!")
    $ listOfYoutube.append(video91)
    default video92 = splunk_video("https://www.youtube.com/watch?v=VOVx9qPg8a0", "Splunk - Displaying Search Results in Custom HTML Tables", "The results of queries can be converted into a token that can later be used in other panels and parts of your dashboards.")
    $ listOfYoutube.append(video92)
    default video93 = splunk_video("https://www.youtube.com/watch?v=ORspN0unmpo", "Splunk IT Service Intelligence Training | Services Overview", "Join this channel to get access to early release of videos and exclusive training videos that will help make you L.A.M.E. ninja: ...")
    $ listOfYoutube.append(video93)
    default video94 = splunk_video("https://www.youtube.com/watch?v=5YXjmQpJEjw", "Splunk Stats Command Tutorial", "The stats command can be used to leverage mathematics to better understand your data. This tutorial will show many of the ...")
    $ listOfYoutube.append(video94)
    default video95 = splunk_video("https://www.youtube.com/watch?v=v_j3eR3Rs-s", "Splunk IT Service Intelligence Training | ITSI Entities", "Join this channel to get access to early release of videos and exclusive training videos that will help make you L.A.M.E. ninja: ...")
    $ listOfYoutube.append(video95)
    default video96 = splunk_video("https://www.youtube.com/watch?v=jPF-RQw965M", "Using Custom Apps to Control Change Management in Splunk", "Custom Apps can contain .conf file changes that can be used to configure Splunk instances. These custom apps can be deployed ...")
    $ listOfYoutube.append(video96)
    default video97 = splunk_video("https://www.youtube.com/watch?v=meQZpscK9g0", "Splunk Tips and Tricks - Detecting Logs Moving to Frozen Bucket", "When indexes.conf settings get filled, the logs move to frozen. It may be useful to be able to set an alert for when logs are moved ...")
    $ listOfYoutube.append(video97)
    default video98 = splunk_video("https://www.youtube.com/watch?v=-qt6mL7tmVc", "Splunk Enterprise Security Free Training | Threat Intel Loading Data Into Local CSVs", "L.A.M.E. Creations has scoured the internet for guidance on the Enterprise Security SIEM from Splunk but has found most of the ...")
    $ listOfYoutube.append(video98)
    default video99 = splunk_video("https://www.youtube.com/watch?v=X2VgHs0Emvs", "Math Functions Within PowerShell", "PowerShell natively handles many Math Functions. This video will show you some of the math functions available within ...")
    $ listOfYoutube.append(video99)
    default video100 = splunk_video("https://www.youtube.com/watch?v=7GFwqpdVmz0", "Master Splunk: Access Saved Searches via REST API – Step-by-Step Guide!", "Welcome to our channel! In this video, we explore how to leverage the Splunk REST API to view and manage saved searches.")
    $ listOfYoutube.append(video100)
    default video101 = splunk_video("https://www.youtube.com/watch?v=XzKbBYY8CDs", "Splunk IT Service Intelligence Training | Glass Panels", "Join this channel to get access to early release of videos and exclusive training videos that will help make you L.A.M.E. ninja: ...")
    $ listOfYoutube.append(video101)
    default video102 = splunk_video("https://www.youtube.com/watch?v=1ZfhIlU5HzA", "Splunk Sort Command SPL", "Splunk Tutorial discussing how to use the Sort Command in SPL searches Join this channel to get access to early release of ...")
    $ listOfYoutube.append(video102)
    default video103 = splunk_video("https://www.youtube.com/watch?v=Dbvx-98PeL0", "Splunk Enterprise Security Free Training | Creating Custom Use Cases", "L.A.M.E. Creations has scoured the internet for guidance on the Enterprise Security SIEM from Splunk but has found most of the ...")
    $ listOfYoutube.append(video103)
    default video104 = splunk_video("https://www.youtube.com/watch?v=Z-OPVR61bJY", "Master Splunk Dashboards: Expert Guide to Troubleshooting Tokens!", "Struggling with tokens on your Splunk dashboard? In this video, we'll dive deep into troubleshooting and fixing common token ...")
    $ listOfYoutube.append(video104)
    default video105 = splunk_video("https://www.youtube.com/watch?v=oMmDkvTBxBo", "Splunk Index Command Tutorial", "This video will give a basic explanation on why Splunk uses multiple indexes and how to search the logs in one or more indexes ...")
    $ listOfYoutube.append(video105)
    default video106 = splunk_video("https://www.youtube.com/watch?v=DCA2ALv7PKo", "L.A.M.E. Quick Guide Ren&#39;&#39;py Security Tool to Learn Splunk and Other Cyber Security Toosl", "https://lamecreations.itch.io/lame-quick-guide Price is free - Itch always asks if you want to donate to the app creator. All donations ...")
    $ listOfYoutube.append(video106)
    default video107 = splunk_video("https://www.youtube.com/watch?v=_w_Wh74k_P0", "Splunk System Admin Interview Preparation | indexes.conf Common Settings", "A sound understanding of the props files that governs your Splunk instance is an invaluable skill for any splunk admin. This and ...")
    $ listOfYoutube.append(video107)
    default video108 = splunk_video("https://www.youtube.com/watch?v=nABCDQmdwzs", "Master Splunk DB Connect: Unleash Your Data&#39;s Potential!&quot;", "Unlock the power of your data with our detailed guide on Splunk DB Connect! This video is your go-to tutorial for learning how to ...")
    $ listOfYoutube.append(video108)
    default video109 = splunk_video("https://www.youtube.com/watch?v=5ZXz-xOKxBU", "Cribl Logstream Product Overview", "Cribl Logstream is a must have product that should be implemented in any home network. The free version of this product ...")
    $ listOfYoutube.append(video109)
    default video110 = splunk_video("https://www.youtube.com/watch?v=z-eaJ9daxTs", "Splunk Tutorial | Subsearch Using Results from Two Indexes #FADS", "Playlist Link for All Daily Trainings https://www.youtube.com/playlist?list=PLFF93FRoUwXGPIh4E5mBvbVxrpjGRUqIO Log ...")
    $ listOfYoutube.append(video110)
    default video111 = splunk_video("https://www.youtube.com/watch?v=-UP4xzdzwXI", "Splunk KV Lookups", "Splunk allows multiple lookup types. This tutorial will cover how to use Key Value files to create lookups. We will demo how to ...")
    $ listOfYoutube.append(video111)
    default video112 = splunk_video("https://www.youtube.com/watch?v=MbnuUtWbVMI", "Splunk IT Service Intelligence Training | ITSI Alerting", "Join this channel to get access to early release of videos and exclusive training videos that will help make you L.A.M.E. ninja: ...")
    $ listOfYoutube.append(video112)
    default video113 = splunk_video("https://www.youtube.com/watch?v=qpY4Qieqewc", "Splunk Table / Field Command", "Splunk tutorial outlining when and how to use the Splunk Table and Fields Commands. Join this channel to get access to early ...")
    $ listOfYoutube.append(video113)
    default video114 = splunk_video("https://www.youtube.com/watch?v=q7RcPwrVMdg", "Explore My Latest Splunk Masterclasses &amp; Books - Exclusive Discounts Inside!", "I'm thrilled to share with you some of my latest creations designed to supercharge your Splunk expertise. By using my special links ...")
    $ listOfYoutube.append(video114)
    default video115 = splunk_video("https://www.youtube.com/watch?v=E9Pl4atRIU0", "Dashboard Naming Done Right: Splunk Certification Essentials!", "Stuck on Splunk's dashboard naming conventions for your certification? This video breaks down the recommended format: • Why ...")
    $ listOfYoutube.append(video115)
    default video116 = splunk_video("https://www.youtube.com/watch?v=W392O2rJKIw", "Splunk Data Models and How to Leverage EventTypes", "Datamodels are a valuable tool in Splunk and through the usage of eventtypes, an analyst can gain a lot of powerful tools to ...")
    $ listOfYoutube.append(video116)
    default video117 = splunk_video("https://www.youtube.com/watch?v=6c-uTI7-cLI", "Introduction to Splunk Free Analytics Daily Queries | Get All Indexes", "We are going to start rolling out a Free Analytic Daily Share (F.A.D.S). We will be adding a video the the playlist each day with an ...")
    $ listOfYoutube.append(video117)
    default video118 = splunk_video("https://www.youtube.com/watch?v=x2ugNlDfI24", "Microsoft PowerShell For Beginners | Using Passwords in Your Scripts and How to Protect the Password", "A beginner tutorial on how to use Microsoft PowerShell and how to use passwords in your script without having the password be ...")
    $ listOfYoutube.append(video118)
    default video119 = splunk_video("https://www.youtube.com/watch?v=elyOotImqgc", "Master Splunk: Create Quick &amp; Responsive Dashboards with the Collect Command &amp; Scheduled Searches!", "Unlock the power of Splunk dashboards with our step-by-step guide on using the collect command and scheduled searches.")
    $ listOfYoutube.append(video119)
    default video120 = splunk_video("https://www.youtube.com/watch?v=CzKIRNQAmIg", "Splunk Tutorial | Search Splunk Search History for SPL Queries #FADS", "To view all videos in the playlist on Splunk Tutorials for Creating Searches use the link: ...")
    $ listOfYoutube.append(video120)
    default video121 = splunk_video("https://www.youtube.com/watch?v=kBs7e4wGQnk", "How to Migrate Splunk from One Operating System to Another", "This tutorial will briefly explain how to move apps from one system to another so you can change the base operating system of ...")
    $ listOfYoutube.append(video121)
    default video122 = splunk_video("https://www.youtube.com/watch?v=zZQNd7LfJtY", "Udemy Course for Mastering Splunk: CIM Compliance, Data Models, and Tstats", "Coupon Code to get this Udemy Course for 12.99 USD B1046EE2BB83384A5657 Link to Udemy Course ...")
    $ listOfYoutube.append(video122)
    default video123 = splunk_video("https://www.youtube.com/watch?v=BCgWc-k2ciU", "Splunk Tutorial | Subsearch / Join Using a Lookup #FADS", "Playlist Link for All Daily Trainings https://www.youtube.com/playlist?list=PLFF93FRoUwXGPIh4E5mBvbVxrpjGRUqIO Log ...")
    $ listOfYoutube.append(video123)
    default video124 = splunk_video("https://www.youtube.com/watch?v=j_l86ePqJEk", "Free Splunk Tutorial on Earliest and Latest Command", "This video will cover how to set the earliest and latest times for a splunk query in the actual query. This is part of a Splunk Tutorial ...")
    $ listOfYoutube.append(video124)
    default video125 = splunk_video("https://www.youtube.com/watch?v=R275B-plQLI", "Splunk Tutorial For Beginners | Common Mistakes | Deploying CSV Lookups with a Deployment Server", "The time may arise that a person decides to push a CSV Lookup to a remote Splunk system using a Deployment Server. A major ...")
    $ listOfYoutube.append(video125)
    default video126 = splunk_video("https://www.youtube.com/watch?v=4zssb06JrsQ", "Splunk Tutorial | Manipulating Multivalue Fields #FADS", "Playlist Link for All Daily Trainings https://www.youtube.com/playlist?list=PLFF93FRoUwXGPIh4E5mBvbVxrpjGRUqIO Log ...")
    $ listOfYoutube.append(video126)
    default video127 = splunk_video("https://www.youtube.com/watch?v=jhE8QFgDW-o", "Splunk Search / Where Command SPL", "A Splunk tutorial on how to use the Search and Where commands in an SPL search Join this channel to get access to early ...")
    $ listOfYoutube.append(video127)
    default video128 = splunk_video("https://www.youtube.com/watch?v=WHfEmd7dmc0", "Free Splunk Tutorial Using Stats and Time to Find Anomalies", "This video will break down a simple process to look for new activity in logs using the stats \"earliest\" command. You can use this ...")
    $ listOfYoutube.append(video128)
    default video129 = splunk_video("https://www.youtube.com/watch?v=gBG0SeWc4PU", "PowerShell Looping Examples", "Powershell uses Do while, Do Until, foreach and for loops. This tutorial will demonstrate how to use each of those loops in ...")
    $ listOfYoutube.append(video129)
    default video130 = splunk_video("https://www.youtube.com/watch?v=Ru0_ChM5IgM", "How to Ingest, Parse, and Make Useful Dashboards from Systems When No Splunkbase App Exists", "This is a real case scenario of taking a tool that I use every day (WeKan) and how to get information out of that system and get it ...")
    $ listOfYoutube.append(video130)
    default video131 = splunk_video("https://www.youtube.com/watch?v=mCUEcSlAE9Y", "Improving Splunk Dashboard Performance Using Base Searches", "Please refer to the link below to get part 1 of this video where we detail how to create the user input and tokens used in this ...")
    $ listOfYoutube.append(video131)
    default video132 = splunk_video("https://www.youtube.com/watch?v=pyOTqXhGeN0", "Cribl Log Stream Example of Sending Syslog to FileStore", "This is a video playlist that will cover how to use the Cribl Stream Product. While the product has limitless capabilities, we will ...")
    $ listOfYoutube.append(video132)
    default video133 = splunk_video("https://www.youtube.com/watch?v=5ID9u6KAyCE", "Mastering SPL: Unlock the Power of the Search Command in Splunk!", "Ready to level up your Splunk skills? In today's video, we're diving deep into the heart of SPL with the essential \"search\" ...")
    $ listOfYoutube.append(video133)
    default video134 = splunk_video("https://www.youtube.com/watch?v=kEpUMT24Ekc", "Mastering Splunk Lookups: How to Search &amp; Filter Data Like a Pro!", "In this video, we'll walk you through how to search and filter data in a Splunk lookup file. Learn the key steps to efficiently extract, ...")
    $ listOfYoutube.append(video134)
    default video135 = splunk_video("https://www.youtube.com/watch?v=ELbX5KJFY_E", "Splunk Enterprise Security Free Training | Enterprise Security vs Splunk Enterprise Clarification", "There has been confusion about Splunk Enterprise and Enterprise Security. This video will attempt to clarify the two. This is a ...")
    $ listOfYoutube.append(video135)
    default video136 = splunk_video("https://www.youtube.com/watch?v=8ryQGIjXrbE", "Unlock the Power of Splunk with the Lookup Editor App: A Comprehensive Guide", "Welcome to our in-depth tutorial on the Lookup Editor App for Splunk! In this video, we will guide you through the features and ...")
    $ listOfYoutube.append(video136)
    default video137 = splunk_video("https://www.youtube.com/watch?v=1DNEypB13Uo", "Cribl Log Stream Tutorial - Setting Up Cribl to Ingest Syslog", "This is a video playlist that will cover how to use the Cribl Stream Product. While the product has limitless capabilities, we will ...")
    $ listOfYoutube.append(video137)
    default video138 = splunk_video("https://www.youtube.com/watch?v=xFktn8bG_9k", "Master SPL Basics: When to Use the where vs search Command!", "Are you ready to level up your Splunk skills? In this tutorial, we dive deep into one of the most commonly asked questions in ...")
    $ listOfYoutube.append(video138)
    default video139 = splunk_video("https://www.youtube.com/watch?v=IFZ8cofDgxg", "Splunk Data Models and Tags", "Tutorial on how to tag data in Splunk. This tutorial will cover potential ideas of how tagging data can create valuable searching ...")
    $ listOfYoutube.append(video139)
    default video140 = splunk_video("https://www.youtube.com/watch?v=w7Jc_DHF3_o", "Cribl Log Stream Tutorials Destinations and Sources Explained", "This is a video playlist that will cover how to use the Cribl Stream Product. While the product has limitless capabilities, we will ...")
    $ listOfYoutube.append(video140)
    default video141 = splunk_video("https://www.youtube.com/watch?v=BNo6FeqA7IE", "Splunk Tutorial | Subsearch Using a CSV Lookup #FADS", "Playlist Link for All Daily Trainings https://www.youtube.com/playlist?list=PLFF93FRoUwXGPIh4E5mBvbVxrpjGRUqIO Log ...")
    $ listOfYoutube.append(video141)
    default video142 = splunk_video("https://www.youtube.com/watch?v=FvHvqxLl4vU", "Powershell on Linux?  Why", "Powershell is a great tool to have in your log analysis tool box. Powershell provides an object oriented approach to handling ...")
    $ listOfYoutube.append(video142)
    default video143 = splunk_video("https://www.youtube.com/watch?v=bk0c3DBpwDM", "PowerShell Functions and Examples", "This tutorial will demonstrate why Functions are used in PowerShell and how to create them. Parameter passing and returning ...")
    $ listOfYoutube.append(video143)
    default video144 = splunk_video("https://www.youtube.com/watch?v=j0oip3AqSJo", "Splunk Data Models Restricting to Specified Indexes", "Splunk Datamodels - especially if they are accelerated - need to be restricted to specified indexes to increase performance.")
    $ listOfYoutube.append(video144)
    default video145 = splunk_video("https://www.youtube.com/watch?v=El87Pyl-buY", "Splunk Tips and Tricks | Hot, Cold, and Warm Buckets Explained", "Splunk indexes data to buckets. This video will focus on helping provide an understanding of how the bukets store data, how they ...")
    $ listOfYoutube.append(video145)
    default video146 = splunk_video("https://www.youtube.com/watch?v=hYvA6lwQozo", "Splunk Tutorial For Beginners | Stats vs Chart Command in Splunk", "This video is an audience request to outline the difference between the stats command and the chart command. This video will ...")
    $ listOfYoutube.append(video146)
    default video147 = splunk_video("https://www.youtube.com/watch?v=ycALxeB0yYs", "Mastering SPL Splunk Queries with ChatGPT: A Step-by-Step Guide", "Welcome to our channel! In this video, we delve into the powerful combination of ChatGPT and Splunk to simplify the process of ...")
    $ listOfYoutube.append(video147)
    default video148 = splunk_video("https://www.youtube.com/watch?v=J1MUtJ45GoE", "Unlock Splunk Secrets: Dashboard Editing Mastery - Deep Dive", "Ready to ace your Splunk certification? Dive into this essential tutorial where we dissect a critical question about Splunk ...")
    $ listOfYoutube.append(video148)
    default video149 = splunk_video("https://www.youtube.com/watch?v=SymQ-I-4xog", "Mastering the Stats Command in Splunk: Your Ultimate Guide to Data Insights!", "Unlock the full potential of your data with Splunk's powerful stats command! In this tutorial, we'll break down the stats command ...")
    $ listOfYoutube.append(video149)
    default video150 = splunk_video("https://www.youtube.com/watch?v=zbYzcDBWGGs", "Splunk Enterprise Security Free Training | Integrating SOAR into Enterprise Security", "L.A.M.E. Creations has scoured the internet for guidance on the Enterprise Security SIEM from Splunk but has found most of the ...")
    $ listOfYoutube.append(video150)
    default video151 = splunk_video("https://www.youtube.com/watch?v=AIwQGC672Nw", "Splunk Fundamentals - Ingest Logs and Get Them CIM Compliant | Example 1", "This tutorial will take the PFSense pfblockerng logs and ingest them into Splunk through Cribl. We will discuss how to get a ...")
    $ listOfYoutube.append(video151)
    default video152 = splunk_video("https://www.youtube.com/watch?v=GlylYn1bj7c", "Splunk Tutorial StrpTime StrfTime Epoch Time Conversion Functions", "We will discuss how to change time from human readable form to epoch and from epoch time to human readable. F.A.D.S tutorial ...")
    $ listOfYoutube.append(video152)
    default video153 = splunk_video("https://www.youtube.com/watch?v=bw4X9gDxqRA", "Unlock Splunk Secrets: Dashboard Editing Mastery - Certification Prep!", "Ready to ace your Splunk certification? Dive into this essential tutorial where we dissect a critical question about Splunk ...")
    $ listOfYoutube.append(video153)
    default video154 = splunk_video("https://www.youtube.com/watch?v=mNAAZ3XGSng", "Splunk Tutorial | Save Results to a Summary Index #FADS", "Playlist Link for All Daily Trainings https://www.youtube.com/playlist?list=PLFF93FRoUwXGPIh4E5mBvbVxrpjGRUqIO Log ...")
    $ listOfYoutube.append(video154)
    default video155 = splunk_video("https://www.youtube.com/watch?v=oKk_dCVjb1A", "Creating a Custom Indexes.conf File to Configure Splunk instances", "This is the second part of how to use conf files to manage the configuration management of Splunk instances. This video will focus ...")
    $ listOfYoutube.append(video155)
    default video156 = splunk_video("https://www.youtube.com/watch?v=cqXbiLobVP8", "How to Configure Splunk to Ingest HTTP Event Collection (HEC)", "Join this channel to get access to perks: https://www.youtube.com/channel/UCdSFSscTkK8oGd_kD_eENFw/join.")
    $ listOfYoutube.append(video156)
    default video157 = splunk_video("https://www.youtube.com/watch?v=CTPdPKNDrVs", "Master Splunk Installs: Easy Guide to DEB &amp; RPM Install/Uninstall!", "Want to master Splunk installations and uninstalls? In this video, we'll walk you through the step-by-step process of installing and ...")
    $ listOfYoutube.append(video157)
    default video158 = splunk_video("https://www.youtube.com/watch?v=sjUeggxdI2g", "Splunk Data Model Field Aliasing", "Splunk Data Models require that your splunk fields match the data model. This video demonstrates how to alias your existing ...")
    $ listOfYoutube.append(video158)
    default video159 = splunk_video("https://www.youtube.com/watch?v=sH_HvuLbKK0", "Splunk Tutorial on Upgrading OS of Splunk | RHEL 7 to RHEL 9", "For those who actually read the description, I apologize for the misleading title on this video. This is a video requested by one of ...")
    $ listOfYoutube.append(video159)
    default video160 = splunk_video("https://www.youtube.com/watch?v=4MuX02yfXK0", "Splunk Tips and Tricks | How to Join Two Sourcetypes Together", "It is often helpful to be able to combine the results of two sourcetypes into one log. This tutorial will show the proper way to perform ...")
    $ listOfYoutube.append(video160)
    default video161 = splunk_video("https://www.youtube.com/watch?v=Q2dG9vwqgoI", "Splunk Chart Command Tutorial", "Splunk tutorial on how to use the chart command in an SPL query. Join this channel to get access to early release of videos and ...")
    $ listOfYoutube.append(video161)
    default video162 = splunk_video("https://www.youtube.com/watch?v=fHOXo2PK-Qs", "Splunk IT Service Intelligence Training | ITSI Overview", "Free training for IT Service Intelligence which is Splunk's pay for app to monitor services and KPIs on your network. This video ...")
    $ listOfYoutube.append(video162)
    default video163 = splunk_video("https://www.youtube.com/watch?v=iFqz9aIfGAI", "Anomaly Detection So Easy Your Grandma Can Do It. No ML degree Required Splunk .conf 2024 Rehearsal", "This video is the dry run rehearsal for the Splunk .Conf 2024 presentation on creating baselines to detect anomalies in your ...")
    $ listOfYoutube.append(video163)
    default video164 = splunk_video("https://www.youtube.com/watch?v=1BdnU51wPfs", "Splunk and Automatic Lookups", "This tutorial will demonstrate how to automatically attach a lookup and its data to a splunk query through the use of automatic ...")
    $ listOfYoutube.append(video164)
    default video165 = splunk_video("https://www.youtube.com/watch?v=a-xOcKPuf3o", "Splunk Enterprise Security Free Training | Risk Based Approach RBA Overview", "L.A.M.E. Creations has scoured the internet for guidance on the Enterprise Security SIEM from Splunk but has found most of the ...")
    $ listOfYoutube.append(video165)
    default video166 = splunk_video("https://www.youtube.com/watch?v=8xTgLftG26E", "Splunk Tips and Tricks | Easily Return the First Value from each Sourcetype in One Query", "This quick tip will help you find the first value from multiple sourcetypes with just one query. This is a time saver to get a better ...")
    $ listOfYoutube.append(video166)
    default video167 = splunk_video("https://www.youtube.com/watch?v=fAt-HqPir0Y", "Splunk Meta Sourcetype Tutorial", "Splunk tutorial on the metadata field sourcetype. Join this channel to get access to early release of videos and exclusive training ...")
    $ listOfYoutube.append(video167)
    default video168 = splunk_video("https://www.youtube.com/watch?v=pooswh6qdQw", "&quot;Top 3 Free Splunk Apps You Need to Know About in 2024!&quot;", "Title: Top 3 Free Splunk Apps You Need to Know About in 2024!** **Description:** Welcome to our latest video where we unveil ...")
    $ listOfYoutube.append(video168)
    default video169 = splunk_video("https://www.youtube.com/watch?v=ZiNCRsUE7LQ", "How to Setup a Splunk Indexer Cluster in Less than 17 minutes", "This is not a tutorial on \"how\" to set up Splunk, it is a demo of actually doing the entire process in under 16 minutes. I start with 6 ...")
    $ listOfYoutube.append(video169)
    default video170 = splunk_video("https://www.youtube.com/watch?v=WOdajjO2vY4", "Log Analysis Made Easy Splunk Training App", "L.A.M.E. Training has put together an app on Splunk base that takes the lessons taught about how to use Splunk and combines ...")
    $ listOfYoutube.append(video170)
    default video171 = splunk_video("https://www.youtube.com/watch?v=nJp6c5YEjwA", "Splunk Enterprise Security Free Training | Network Traffic Data Model", "L.A.M.E. Creations has scoured the internet for guidance on the Enterprise Security SIEM from Splunk but has found most of the ...")
    $ listOfYoutube.append(video171)
    default video172 = splunk_video("https://www.youtube.com/watch?v=cqbzwmxlIOM", "Splunk Tutorial | Quickly Search All Hosts Sending Logs to Splunk #FADS", "Playlist Link for All Daily Trainings https://www.youtube.com/playlist?list=PLFF93FRoUwXGPIh4E5mBvbVxrpjGRUqIO Log ...")
    $ listOfYoutube.append(video172)
    default video173 = splunk_video("https://www.youtube.com/watch?v=BXlL5yFOA9k", "Splunk System Admin Interview Preparation | Outputs.conf Common Settings", "A sound understanding of the props files that governs your Splunk instance is an invaluable skill for any splunk admin. This and ...")
    $ listOfYoutube.append(video173)
    default video174 = splunk_video("https://www.youtube.com/watch?v=v8-vgovBceU", "How to Upgrade to a Newer Version of Splunk", "Regardless of operating system, one day you will have to update your Splunk version. This tutorial will show you how to upgrade ...")
    $ listOfYoutube.append(video174)
    default video175 = splunk_video("https://www.youtube.com/watch?v=nWoTiVo5wyI", "Splunk Enterprise Security Free Training | Using Threat Intelligence", "L.A.M.E. Creations has scoured the internet for guidance on the Enterprise Security SIEM from Splunk but has found most of the ...")
    $ listOfYoutube.append(video175)
    default video176 = splunk_video("https://www.youtube.com/watch?v=Grqd9Dbic4s", "Splunk Tutorials | iplocation visualization #FADS", "Playlist Link for All Daily Trainings https://www.youtube.com/playlist?list=PLFF93FRoUwXGPIh4E5mBvbVxrpjGRUqIO We are ...")
    $ listOfYoutube.append(video176)
    default video177 = splunk_video("https://www.youtube.com/watch?v=zlX4QDrp8c8", "Cribl Handling XML Windows Event Logs", "If you handle XML Windows EventLogs, you probably agree that the logs are hard to parse and are verbose. They take up a large ...")
    $ listOfYoutube.append(video177)
    default video178 = splunk_video("https://www.youtube.com/watch?v=nr9cdl7LcSk", "Unlock the Power of Timechart in Splunk! | SPL Tutorial for Data-Driven Insights", "Want to take your Splunk skills to the next level? Learn how to use the timechart command to visualize data trends over time like a ...")
    $ listOfYoutube.append(video178)
    default video179 = splunk_video("https://www.youtube.com/watch?v=6PjNibpJxyQ", "Gravwell - A Modern Alternative to Splunk and Elastic for Log Collection | Overview", "Gravwell is an alternative to Elastic and Splunk that was started in the last few years. This software provides the same abilities that ...")
    $ listOfYoutube.append(video179)
    default video180 = splunk_video("https://www.youtube.com/watch?v=4989_n12cms", "Cribl Stream Tutorial How To Install as Syslog Server", "This is a video playlist that will cover how to use the Cribl Stream Product. While the product has limitless capabilities, we will ...")
    $ listOfYoutube.append(video180)
    default video181 = splunk_video("https://www.youtube.com/watch?v=kSEYA1sN0Cw", "Splunk Tutorials | iplocation - geographical mapping of ip addresses #FADS", "Playlist Link for All Daily Trainings https://www.youtube.com/playlist?list=PLFF93FRoUwXGPIh4E5mBvbVxrpjGRUqIO We are ...")
    $ listOfYoutube.append(video181)
    default video182 = splunk_video("https://www.youtube.com/watch?v=kSzBtr8SkHQ", "Splunk Free Tutorial | How to Replay Events With Eventgen", "Join this channel to get access to perks: https://www.youtube.com/channel/UCdSFSscTkK8oGd_kD_eENFw/join.")
    $ listOfYoutube.append(video182)
    default video183 = splunk_video("https://www.youtube.com/watch?v=plKBAmYzobg", "ProxMox Tutorial | How to Enable Promiscuous Mode", "Join this channel to get access to perks: https://www.youtube.com/channel/UCdSFSscTkK8oGd_kD_eENFw/join.")
    $ listOfYoutube.append(video183)
    default video184 = splunk_video("https://www.youtube.com/watch?v=TSr1WjFlgYA", "Splunk Head Command Tutorial", "Splunk Tutorial on how to use the Head command. Join this channel to get access to early release of videos and exclusive ...")
    $ listOfYoutube.append(video184)
    default video185 = splunk_video("https://www.youtube.com/watch?v=PbvIxkPy9Uc", "Mastering Splunk Dashboards: A Complete Guide to the Dashboard Example App from Splunkbase", "Welcome to our comprehensive tutorial on the Dashboard Example App from Splunkbase! In this video, we will walk you through ...")
    $ listOfYoutube.append(video185)
    default video186 = splunk_video("https://www.youtube.com/watch?v=J5Dwae7jw-M", "Splunk Enterprise Security Free Training | Network Traffic Data Model CIM Compliant", "L.A.M.E. Creations has scoured the internet for guidance on the Enterprise Security SIEM from Splunk but has found most of the ...")
    $ listOfYoutube.append(video186)
    default video187 = splunk_video("https://www.youtube.com/watch?v=FTlqlqJLXpY", "Splunk How to Convert a Search Query Into a Tstats Query", "Splunk Tstats query can be confusing when you first start working with them. This video will focus on how a Tstats query is written ...")
    $ listOfYoutube.append(video187)
    default video188 = splunk_video("https://www.youtube.com/watch?v=-v7hVZpAqrw", "Splunk Enterprise Security Free Training | Intro To Enterprise Security", "L.A.M.E. Creations has scoured the internet for guidance on the Enterprise Security SIEM from Splunk but has found most of the ...")
    $ listOfYoutube.append(video188)
    default video189 = splunk_video("https://www.youtube.com/watch?v=CWOMhSD2LO8", "Master Splunk Lookups: Unleash the Power of Wildcards!", "Unlock the full potential of your Splunk searches with wildcards in lookups! In this video, we'll dive into the power of using ...")
    $ listOfYoutube.append(video189)
    default video190 = splunk_video("https://www.youtube.com/watch?v=rS7CyUgG4sI", "Splunk Enterprise Security Free Training | Correlation Searches", "L.A.M.E. Creations has scoured the internet for guidance on the Enterprise Security SIEM from Splunk but has found most of the ...")
    $ listOfYoutube.append(video190)
    default video191 = splunk_video("https://www.youtube.com/watch?v=kIdy8i6s8lo", "Splunk System Admin Interview Preparation | web.conf Common Settings", "A sound understanding of the props files that governs your Splunk instance is an invaluable skill for any splunk admin. This and ...")
    $ listOfYoutube.append(video191)
    default video192 = splunk_video("https://www.youtube.com/watch?v=e1AROh8HuXI", "Splunk System Admin Interview Preparation | analyticstory.conf Common Settings", "A sound understanding of the props files that governs your Splunk instance is an invaluable skill for any splunk admin. This and ...")
    $ listOfYoutube.append(video192)
    default video193 = splunk_video("https://www.youtube.com/watch?v=Uhv7p12n63A", "Splunk Tutorial For Beginners | Creating a Basic EventGen System in Splunk", "The ability to have Splunk generate logs for a development system can be an integral part of creating a training environment for ...")
    $ listOfYoutube.append(video193)
    default video194 = splunk_video("https://www.youtube.com/watch?v=Rx7d47ilkIw", "Splunk Timechart SPL Tutorial", "Splunk tutorial on how to use the timechart, how to implement span, and the timewrap command Visit our discord channel to post ...")
    $ listOfYoutube.append(video194)
    default video195 = splunk_video("https://www.youtube.com/watch?v=mtrJpfPNsqk", "Splunk Tutorial For Beginners on Windows | Cyber Security Tools", "Are you interested in learning or increasing your skills in CyberSecurity. Splunk is an invaluable tool in the CyberSecurity tool belt.")
    $ listOfYoutube.append(video195)
    default video196 = splunk_video("https://www.youtube.com/watch?v=pcm-Ne_e09Q", "Splunk App Development - How to simplify merging local settings into the default settings", "Splunk base and best practice require that the local config files be moved into the default directory. If you are copying and pasting ...")
    $ listOfYoutube.append(video196)
    default video197 = splunk_video("https://www.youtube.com/watch?v=nHjbuFFKfKI", "Prize Giveaway for LAME Brain Trust Members", "Thank you LAME Creation Members for your support of my channel. Your support has helped me be able to make my dreams of ...")
    $ listOfYoutube.append(video197)
    default video198 = splunk_video("https://www.youtube.com/watch?v=TP209M2vYVQ", "Improve Your Splunk Lookups | Wildcards, Case Sensitivity and Bulk Updates Explained", "Join this channel to get access to perks: https://www.youtube.com/channel/UCdSFSscTkK8oGd_kD_eENFw/join.")
    $ listOfYoutube.append(video198)
    default video199 = splunk_video("https://www.youtube.com/watch?v=MWhDFm1BGXo", "Splunk Filtering to the Left", "Splunk tutorial on how to use filtering and the importance of doing it as soon as possible. This is part of a Splunk Tutorial Playlist to ...")
    $ listOfYoutube.append(video199)
    default video200 = splunk_video("https://www.youtube.com/watch?v=rXywsH_D4Sw", "How To Use A Splunk Deployment Server to Push Out Apps for Data Ingestion", "This is the second video in my playlist on how to ingest new logs into Splunk. This video will cover how to use a deployment ...")
    $ listOfYoutube.append(video200)
    default video201 = splunk_video("https://www.youtube.com/watch?v=98B9UmFr0qs", "Sysmon: How to Install And Set Up Sysmon", "Tutorial on how to install Sysmon on a Windows Box using the Microsoft Store and downloading the zip file. We also provide Swift ...")
    $ listOfYoutube.append(video201)
    default video202 = splunk_video("https://www.youtube.com/watch?v=79tRoS_1-bo", "&quot;Unlock Splunk&#39;s Power: Mastering the Add-On Builder in Under an Hour!", "Dive into the world of Splunk with our ultimate guide to the Add-On Builder! Whether you're a Splunk newbie or a seasoned pro ...")
    $ listOfYoutube.append(video202)
    default video203 = splunk_video("https://www.youtube.com/watch?v=NXmtncK-dnY", "How to Detect Future Logs in Splunk | Complete Tutorial", "In this tutorial, we dive deep into how to detect and troubleshoot future-dated logs in Splunk. Logs with timestamps in the future ...")
    $ listOfYoutube.append(video203)
    default video204 = splunk_video("https://www.youtube.com/watch?v=yUgjdUXuD3w", "Splunk Tutorial | Searching For Failed Logins Within Splunk UI #FADS", "To view all videos in the playlist on Splunk Tutorials for Creating Searches use the link: ...")
    $ listOfYoutube.append(video204)
    default video205 = splunk_video("https://www.youtube.com/watch?v=u6rWLk7wvRw", "Creating a Domain Controller Using Powershell Scripting", "Powershell scripts are the key to automation. Using scripts allows for quickly setting up infrastructure and also building test ...")
    $ listOfYoutube.append(video205)
    default video206 = splunk_video("https://www.youtube.com/watch?v=XnCEZTKOm90", "Splunk Universal Forwarder Tutorial - How to send Syslog to Splunk", "We will discuss how syslog and the Splunk universal forwarder are similar and different and how to utilize both. We will discuss ...")
    $ listOfYoutube.append(video206)
    default video207 = splunk_video("https://www.youtube.com/watch?v=36RjwmJ_Ee4", "Intro to Splunk SOAR Phantom | Sending Splunk Alerts To SOAR Phantom", "Playlist Link for SOAR Videos https://youtube.com/playlist?list=PLFF93FRoUwXH_7yitxQiSUhJlZE7Ybmfu This is the a ...")
    $ listOfYoutube.append(video207)
    default video208 = splunk_video("https://www.youtube.com/watch?v=phxiwtfFsEA", "Intro to Splunk SOAR Phantom | Setting up the Search App", "Playlist Link for SOAR Videos https://youtube.com/playlist?list=PLFF93FRoUwXH_7yitxQiSUhJlZE7Ybmfu This is the first video of ...")
    $ listOfYoutube.append(video208)
    default video209 = splunk_video("https://www.youtube.com/watch?v=sOEyptSYN_k", "Splunk IT Service Intelligence Training | KPI Overview", "Free training for IT Service Intelligence which is Splunk's pay for app to monitor services and KPIs on your network. This video ...")
    $ listOfYoutube.append(video209)
    default video210 = splunk_video("https://www.youtube.com/watch?v=x4uNWAmVyrU", "Intro to Splunk SOAR Phantom | How To Search Splunk Data in a Playbook", "Playlist Link for SOAR Videos https://youtube.com/playlist?list=PLFF93FRoUwXH_7yitxQiSUhJlZE7Ybmfu This is the a ...")
    $ listOfYoutube.append(video210)
    default video211 = splunk_video("https://www.youtube.com/watch?v=yOd1Kx8P06c", "ProxMox Tutorial on How to Create VMs and Clone VMs", "Join this channel to get access to perks: https://www.youtube.com/channel/UCdSFSscTkK8oGd_kD_eENFw/join.")
    $ listOfYoutube.append(video211)
    default video212 = splunk_video("https://www.youtube.com/watch?v=1alH9hYVB4I", "$12.99 Udemy Course for Splunk IT Service Intelligence From the Ground Up - $12.99 USD", "Coupon Code to get this Udemy Course for 12.99 USD 7A263B97B0C8F55352F0 Link to Udemy Course ...")
    $ listOfYoutube.append(video212)
    default video213 = splunk_video("https://www.youtube.com/watch?v=EcXuBrUkrME", "Cribl Log Stream Tutorial Using Pipelines to Change Syslog and Sending it To Splunk", "This is a video playlist that will cover how to use the Cribl Stream Product. While the product has limitless capabilities, we will ...")
    $ listOfYoutube.append(video213)
    default video214 = splunk_video("https://www.youtube.com/watch?v=TcLyjYdpC6w", "Transform Your Splunk Skills with the Eval Command!", "Ready to unlock a whole new level of data analysis in Splunk? In this tutorial, we'll dive into the Eval Command—one of SPL's ...")
    $ listOfYoutube.append(video214)
    default video215 = splunk_video("https://www.youtube.com/watch?v=bPboX7qnsWU", "Intro to Splunk SOAR Phantom | Making Rest and HTTP actions in a Playbook", "Playlist Link for SOAR Videos https://youtube.com/playlist?list=PLFF93FRoUwXH_7yitxQiSUhJlZE7Ybmfu This is the a ...")
    $ listOfYoutube.append(video215)
    default video216 = splunk_video("https://www.youtube.com/watch?v=QdM6JvnYu7g", "Splunk Enterprise Security Training | Setting up and Installing the App", "Splunk Enterprise Security is an amazing SIEM tool that can simplify many of your security logs, but it is not as simple as just ...")
    $ listOfYoutube.append(video216)
    default video217 = splunk_video("https://www.youtube.com/watch?v=6DbQEa_ylIM", "Splunk Universal Forwarder Tutorial - How to Setup a UF", "This video will cover how to install a universal forwarder on a Linux box. Installation is nearly identical for Windows and the ...")
    $ listOfYoutube.append(video217)
    default video218 = splunk_video("https://www.youtube.com/watch?v=utcCZI-ksOY", "How and When to Create Splunk Indexes", "This tutorial will explain when a new index should be created and how to create a new index in Splunk. This video will cover how ...")
    $ listOfYoutube.append(video218)
    default video219 = splunk_video("https://www.youtube.com/watch?v=DEvJPCGycQI", "How to Use Splunk in Docker", "This tutorial will briefly show how to use Docker to set up a Splunk instance. This is advantageous if you are trying to develop on ...")
    $ listOfYoutube.append(video219)
    default video220 = splunk_video("https://www.youtube.com/watch?v=PrT9l1s9Fv0", "Splunk Rename Tutorial", "Tutorial for Splunk on how to use the Rename command to make fields user friendly, remove unwanted characters, or merge ...")
    $ listOfYoutube.append(video220)
    default video221 = splunk_video("https://www.youtube.com/watch?v=t6EJ2s7deTI", "Splunk Machine Learning Categorization and Anomaly Detection Models", "Join this channel to get access to perks: https://www.youtube.com/channel/UCdSFSscTkK8oGd_kD_eENFw/join This video will ...")
    $ listOfYoutube.append(video221)
    default video222 = splunk_video("https://www.youtube.com/watch?v=Wvi3Fw6RoXs", "Detecting Brute Force Attacks in Splunk: Step-by-Step SPL Tutorials", "01:14 Detect Multiple Failed Logins from Same Computer 03:56 High Volume of Authentication from a Single Computer 04:50 ...")
    $ listOfYoutube.append(video222)
    default video223 = splunk_video("https://www.youtube.com/watch?v=anvfqRfS-Zs", "Splunk and Regex | How Do I Use Regex in My Queries", "Join this channel to get access to perks: https://www.youtube.com/channel/UCdSFSscTkK8oGd_kD_eENFw/join.")
    $ listOfYoutube.append(video223)
    default video224 = splunk_video("https://www.youtube.com/watch?v=4KzFhENC1yY", "Unlock the Power of Table Command in Splunk! | SPL Tutorial for Data-Driven Insights", "In this Let's Learn SPL video, we're diving into the table command! Unlike many other SPL commands that are designed to help ...")
    $ listOfYoutube.append(video224)
    default video225 = splunk_video("https://www.youtube.com/watch?v=nTQRCtIrXXc", "Splunk Enterprise Security Training | Setting up data models to populate dashboards", "Splunk Enterprise Security is an amazing SIEM tool that can simplify many of your security logs, but it is not as simple as just ...")
    $ listOfYoutube.append(video225)
    default video226 = splunk_video("https://www.youtube.com/watch?v=wexcABNriIc", "Level Up Your Splunk Skills: Create Test Data Sets with BOTS v3 &amp; Eventgen!", "Ready to supercharge your Splunk learning at home? In this video, we'll show you how to use the BOTS v3 data set and Eventgen ...")
    $ listOfYoutube.append(video226)
    default video227 = splunk_video("https://www.youtube.com/watch?v=45nJ1yGgz0g", "Intro to Splunk SOAR Phantom | Automating Messages in Splunk", "Playlist Link for SOAR Videos https://youtube.com/playlist?list=PLFF93FRoUwXH_7yitxQiSUhJlZE7Ybmfu This is the a ...")
    $ listOfYoutube.append(video227)
    default video228 = splunk_video("https://www.youtube.com/watch?v=DCxKWee4H48", "Splunk Dashboards and How to Use User Input and Tokens", "Splunk Dashboards are an amazing tool for displaying easy to view and consistent data. This tutorial will show how to create ...")
    $ listOfYoutube.append(video228)
    default video229 = splunk_video("https://www.youtube.com/watch?v=19Wc4VihJD0", "Splunk IT Service Intelligence Training | Using Content Packs to Speed up Creation of Services", "Free training for IT Service Intelligence which is Splunk's pay for app to monitor services and KPIs on your network. This video ...")
    $ listOfYoutube.append(video229)
    default video230 = splunk_video("https://www.youtube.com/watch?v=Oc1FxJXETF0", "Free Network Sensor - Zeek/Bro - Installation and Configuration Instructions", "This is an installation guide for installing and configuring a Zeek Sensor on Ubuntu. I used Zeek 24.04 but it will work on pretty ...")
    $ listOfYoutube.append(video230)
    default video231 = splunk_video("https://www.youtube.com/watch?v=OT9UT5Cidxw", "Intro to Splunk SOAR Phantom | How to Install Splunk SOAR Phantom", "Playlist Link for SOAR Videos https://youtube.com/playlist?list=PLFF93FRoUwXH_7yitxQiSUhJlZE7Ybmfu This is part of a video ...")
    $ listOfYoutube.append(video231)
    default video232 = splunk_video("https://www.youtube.com/watch?v=uB6b_WQYeKA", "Splunk Time Picker And Manipulation", "Splunk tutorial to explain the time picker options and a method for adding or subtracting time from an epoch number. Join this ...")
    $ listOfYoutube.append(video232)
    default video233 = splunk_video("https://www.youtube.com/watch?v=wC1fJn3z4Z8", "How to Upgrade A Splunk Universal Forwarder Tutorial", "Learn how to make an upgrade of your Splunk Universal Forwarder. We demo using a tar file on Linux, but this will work for any ...")
    $ listOfYoutube.append(video233)
    default video234 = splunk_video("https://www.youtube.com/watch?v=c4mewe0rf-8", "Splunk Enterprise Security Free Training | Incident Review - Ticket Triage", "L.A.M.E. Creations has scoured the internet for guidance on the Enterprise Security SIEM from Splunk but has found most of the ...")
    $ listOfYoutube.append(video234)
    default video235 = splunk_video("https://www.youtube.com/watch?v=lkLfJeDz6nk", "Splunk Machine Learning Made Easy", "Join this channel to get access to perks: https://www.youtube.com/channel/UCdSFSscTkK8oGd_kD_eENFw/join This video will ...")
    $ listOfYoutube.append(video235)
    default video236 = splunk_video("https://www.youtube.com/watch?v=JD14OCh8mg4", "Splunk IT Service Intelligence Training | Integrating with 3rd Party Ticketing System", "Join this channel to get access to early release of videos and exclusive training videos that will help make you L.A.M.E. ninja: ...")
    $ listOfYoutube.append(video236)
    default video237 = splunk_video("https://www.youtube.com/watch?v=nJxunAQFA8M", "Using Powershell to Extract Fields from Windows Event Logs", "A problem was raised on how to pull usernames, and times out of logon events in Windows Event Security Logs with Powershell.")
    $ listOfYoutube.append(video237)
    default video238 = splunk_video("https://www.youtube.com/watch?v=SiezFb0L9N0", "Splunk Universal Forwarder Tutorial - Deploying Apps with a Deployment Server", "This video will cover how to install a universal forwarder on a Linux box. Installation is nearly identical for Windows and the ...")
    $ listOfYoutube.append(video238)
    default video239 = splunk_video("https://www.youtube.com/watch?v=gtVQVgkInwk", "Splunk Tutorial on Ingesting Sysmon Logs From Windows", "Tutorial on how to install the Splunk Sysmon TA. We will show where to download the app from splunkbase. Then we will install ...")
    $ listOfYoutube.append(video239)
    default video240 = splunk_video("https://www.youtube.com/watch?v=gd5xDNGEsoU", "Intro to Splunk SOAR Phantom | Using SSH in SOAR Phantom Playbooks", "Playlist Link for SOAR Videos https://youtube.com/playlist?list=PLFF93FRoUwXH_7yitxQiSUhJlZE7Ybmfu This is the a ...")
    $ listOfYoutube.append(video240)
    default video241 = splunk_video("https://www.youtube.com/watch?v=-8G8yXU-n0I", "Creating a Custom App To Get Splunk To Ingest Data", "Getting Data into Splunk is made significantly more simple through the use of a custom app. This video will demonstrate how to ...")
    $ listOfYoutube.append(video241)
    default video242 = splunk_video("https://www.youtube.com/watch?v=olu5-aWgICw", "Intro to Splunk SOAR Phantom | Sending SOAR Event Logs to Splunk", "Playlist Link for SOAR Videos https://youtube.com/playlist?list=PLFF93FRoUwXH_7yitxQiSUhJlZE7Ybmfu This is the a ...")
    $ listOfYoutube.append(video242)
    default video243 = splunk_video("https://www.youtube.com/watch?v=nCqberHxQaI", "Splunk Enterprise Security Free Training | ES Notable Integration Into SOAR In Depth", "L.A.M.E. Creations has scoured the internet for guidance on the Enterprise Security SIEM from Splunk but has found most of the ...")
    $ listOfYoutube.append(video243)
    default video244 = splunk_video("https://www.youtube.com/watch?v=qeVs4p8R6R0", "Splunk Enterprise Security Free Training | Web Data Model CIM Compliance", "L.A.M.E. Creations has scoured the internet for guidance on the Enterprise Security SIEM from Splunk but has found most of the ...")
    $ listOfYoutube.append(video244)
    default video245 = splunk_video("https://www.youtube.com/watch?v=xGiLTayok6c", "Intro to Splunk SOAR Phantom | How to Install Splunk SOAR Phantom", "Join this channel to get access to early release of videos and exclusive training videos that will help make you L.A.M.E. ninja: ...")
    $ listOfYoutube.append(video245)
    default video246 = splunk_video("https://www.youtube.com/watch?v=ycOhk9TTDmI", "Streamline Your Splunk Infrastructure: How to Use Apps &amp; Deployment Server for Effortless Management", "Discover how to take your Splunk environment to the next level with this powerful guide! In this video, we'll show you how to use ...")
    $ listOfYoutube.append(video246)
    default video247 = splunk_video("https://www.youtube.com/watch?v=r11QGm1NbDc", "Splunk Enterprise Security Free Training | Inventory Integration", "L.A.M.E. Creations has scoured the internet for guidance on the Enterprise Security SIEM from Splunk but has found most of the ...")
    $ listOfYoutube.append(video247)
    default video248 = splunk_video("https://www.youtube.com/watch?v=dNTaw2VmpJ4", "Splunk Using Tokens to Perform Completely Different Searches", "Splunk tokens provide lots of capabilities. This video will walk you through the process of creating a dashboard that creates two ...")
    $ listOfYoutube.append(video248)
    default video249 = splunk_video("https://www.youtube.com/watch?v=HJ0OTvSPfwQ", "ProxMox How To Install With Bootable USB", "Join this channel to get access to perks: https://www.youtube.com/channel/UCdSFSscTkK8oGd_kD_eENFw/join.")
    $ listOfYoutube.append(video249)
    default video250 = splunk_video("https://www.youtube.com/watch?v=Iol1CHyv23A", "Splunk Enterprise Security Training | Setting up the Server", "Splunk Enterprise Security is an amazing SIEM tool that can simplify many of your security logs, but it is not as simple as just ...")
    $ listOfYoutube.append(video250)
    default video251 = splunk_video("https://www.youtube.com/watch?v=QtZsbMOnDMA", "Build a Powerful Cyber Detection Tool in Minutes with Simple PowerShell!", "Unleash the Power of PowerShell for Cyber Security! In this video, we'll show you how to create a robust cyber detection tool ...")
    $ listOfYoutube.append(video251)
    default video252 = splunk_video("https://www.youtube.com/watch?v=wb2V5bP7xWw", "Splunk IT Service Intelligence Training | Services Overview Part 2", "Join this channel to get access to early release of videos and exclusive training videos that will help make you L.A.M.E. ninja: ...")
    $ listOfYoutube.append(video252)


  

