label networklogOverview:
    scene darkcyberbg
    show narrator sensai at left 

    n sensai "In this tutorial, we will be discussing Network Logs."
    n sensai "This tutorial will be generic because whereas Host Logs are generated by a standard process, network logs can be generated and collected from numerous different technologies."
    n sensai "Instead of focusing on a particular technology we will discuss tools that capture network logs"
    n sensai "Then we will discuss some of the common things that should be looked for in the network logs"
    n sensai "Firewalls and proxies are two of the most common appliances that will collect Network logs as their very purpose is to monitor and control network flow."
    n sensai "Your own computer can be configured to collect network traffic that goes across your network card."
    n sensai "One of the most common tools to collect network traffic is to use network taps on your network switches and have that data captured as packet capture (pcap)"
    n sensai "Wireshark can be used to review the pcap logs."
     
    n sensai "Tools such as zeek and netflow will help summarize the pcap and provide a much smaller concise log.  Zeek logs are orders of magnitudes smaller than raw pcap files which means the cost to store it will be much less."
    n sensai "Some of the most common things that may be of interest to you in the network logs are the IP tuple connections or basically what machines are trying to talk to other machines."
    n sensai "The ability to see the amount of traffic coming into an IP address and how much is leaving may be valuable because attackers will often try to send large amounts of data out of the network when they compromise a system."
    n sensai "Web / HTTP traffic can be useful, particularly if you can see the status code for the connections.  A bunch of 400 level errors may be an indication of something bad happening on your web server."
    n sensai "If you can see what is being posted to a web server, it may also show directory traversal or other types of malicious activity."
    n sensai "DNS logs can be used to help identify what domains your systems are attempting to connect to."
   
    jump mainMenu

